"""
merge_prompts_and_responses.py

This script merges prompt and response CSVs into aligned instruction-response pairs.

Prompts and responses were generated by an LLM in batches of 100 to enable easier manual review,
prevent duplication, and support iterative prompt refinement. Each file pair is matched via a shared ID field.

"""

import pandas as pd
import os

# Configuration

# Input directories
input_dir_prompts = os.path.expanduser("~/Chaos-Projects/Python/Wednesday/training_data/python/basics/prompts")
input_dir_response= os.path.expanduser("~/Chaos-Projects/Python/Wednesday/training_data/python/basics/responses")

# Output directory
output_dir = os.path.expanduser("~/Chaos-Projects/Python/Wednesday/training_data/python/basics/merged")
num_files = 20 # Total prompt/response pairs to process

os.makedirs(output_dir, exist_ok=True)

# File naming conventions
input_prompt_prefix = "prompt"
input_response_prefix = "response"
output_prefix = "prompt_qa_pairs"

# Merge Loop
for i in range(1, num_files + 1):
    try:
        prompt_path = os.path.join(input_dir_prompts, f"{input_prompt_prefix}{i}.csv")
        response_path = os.path.join(input_dir_response, f"{input_response_prefix}{i}.csv")
        output_path = os.path.join(output_dir, f"{output_prefix}{i}.csv")

        print(f"[INFO] Merging set {i}:")
        print(f"       Prompt:   {prompt_path}")
        print(f"       Response: {response_path}")

        df_prompt = pd.read_csv(prompt_path)
        df_response = pd.read_csv(response_path)

        merged = pd.merge(df_prompt, df_response, on="id", how="inner")

        if merged.empty:
            print(f"[WARNING] No matching IDs found in set {i}. Output will be empty.")
        else:
            merged.to_csv(output_path, index=False)
            print(f"[SUCCESS] Saved merged output to: {output_path}")

    except FileNotFoundError as e:
        print(f"[ERROR] Missing file in set {i}: {e}")
    except Exception as e:
        print(f"[ERROR] Unexpected error with file set {i}: {e}")

# Completion Message
print("\n[FINISHED] Congrats, the data is now less fragmented than your sleep schedule.")
